### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/ionic2-docs#1]
Tradução dos tópicos principais da página inicial.

![ionic2-home](https://cloud.githubusercontent.com/assets/21221/13036271/87dee5ee-d341-11e5-85af-5059f58ecbbd.png)

**Comment by lvdamaceno** [comment]
@lvdamaceno

**Comment by juarezpaf** [comment]
@lvdamaceno você conseguiu evoluir nessa issue?

**Comment by lvdamaceno** [comment]
Boa noite @juarezpaf, fiquei impossibilitado de começar antes as traduções, já enviei, estou vendo o que ainda tem pra fazer para colaborar, caso tenha alguma sugestão do que posso fazer já só dizer. Abraço.
