### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/ionic2-docs#2]
Tradução das seguintes seções:
- [x] @angelobms Welcome `/docs/v2/getting-started/`
- [x] @angelobms Installation `/docs/v2/getting-started/installation/`
- [x] @angelobms Tutorial `/docs/v2/getting-started/tutorial/`
- [x] @angelobms Migration `/docs/v2/getting-started/migration/`
- [x] @angelobms Concepts `/docs/v2/getting-started/concepts/`

**Comment by lvdamaceno** [comment]
Welcome /docs/v2/getting-started/
 Installation /docs/v2/getting-started/installation/
 Tutorial /docs/v2/getting-started/tutorial/
 Migration /docs/v2/getting-started/migration/
 Concepts /docs/v2/getting-started/concepts/

**Comment by angelobms** [comment]
Tradução realizada para este tópico pull request  #11 
Necessário revisar. 
Se possível redirecionar essa Issue para meu usuário.

**Comment by gabrielclima** [comment]
Estou analisando sua tradução @angelobms. 

Assim que eu terminar, vou fazer o `merge` e te avisar.

=)

**Comment by angelobms** [comment]
@juarezpaf , @gabrielclima apenas estou disposto a contribuir. Tenho tempo disponível para realizar as traduções. Aproveito para novamente falar aqui que não tenho o inglês nativo. E dizer que a abordagem feita por você @gabrielclima foi totalmente sem necessidade.

Mais uma vez. Estou tentando contribuir e ajudar no que for possível. Vi em um comentário em uma das issues a dificuldade de encontrar pessoas dispostas a isso.

**Comment by gabrielclima** [comment]
@angelobms, como escrevi na issue de [Discussões Gerais](https://github.com/IonicBrazil/ionic2-docs/issues/9), peço perdão. E, cara... Eu também estou me dispondo a ajudar e contribuir desde o começo desse processo. Quem revisa também tem trabalho.

**Comment by angelobms** [comment]
Tudo bem @gabrielclima. Estamos todos aqui para contribuir e realizar as traduções da melhor forma. 
Então, revisei novamente a tradução feita por mim para os tópicos desse capitulo. Pull request #15

**Comment by angelobms** [comment]
Tradução Getting Started (#2) - Tutorial  disponível para revisão. Pull request #21.
