### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/ionic2-docs#4]
Tradução das seguintes páginas:
- [x] @matheuscas Theming Ionic Apps `/docs/v2/theming/`
- [x] @matheuscas Theming your Ionic App `/docs/v2/theming/theming-your-app/`
- [x] @matheuscas Platform Specific Styles `/docs/v2/theming/platform-specific-styles/`
- [x] @matheuscas Sass Variables `/docs/v2/theming/sass-variables/`
- [x] @matheuscas Overriding Ionic Sass Variables `/docs/v2/theming/overriding-ionic-variables/`

**Comment by matheuscas** [comment]
Eu para essa **issue** aqui, pode ser?

**Comment by gabrielclima** [comment]
Pronto, @matheuscas!

**Comment by gabrielclima** [comment]
Capítulo encerrado!

=)
