### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by juarezpaf** [IonicBrazil/ionic2-docs#6]
- [x] @bernardobrezende Tradução da página _Troubleshooting Your Ionic App_
  `/docs/v2/faq/`

**Comment by bernardobrezende** [comment]
Olá,

Gostaria de fazer essa tradução.

**Comment by gabrielclima** [comment]
Pronto, @bernardobrezende.

**Comment by gabrielclima** [comment]
Capítulo traduzido =)
